fix multiprocessing issues on IBM i
kadler/cpython pull request #3
Opened 2020-01-07 20:51 UTC by ThePrez

Work around IBM i's inability to share named semaphores across a fork

2020-09-24 21:59 UTC, kadler requested changes

2020-09-24 21:59 UTC, kadler commented on Modules/_multiprocessing/semaphore.c
> +#define USE_UNNAMED_SEMAPHORES // can't share named semaphore across fork, so use unnamed instead
Add `#ifdef __PASE__` around it and move to around line 182. Also can define this in the `#ifdef MS_WINDOWS` block below. This simplifies the handling around sem_open in _rebuild.

2020-09-24 21:59 UTC, kadler commented on Modules/_multiprocessing/semaphore.c
> +#if !defined(MS_WINDOWS) && !defined(USE_UNNAMED_SEMAPHORES) // if we're using unnamed, then we got it via fork, can't sem_open
```suggestion
#ifndef USE_UNNAMED_SEMAPHORES
```
Define USE_UNNAMED_SEMAPHORES in the `#ifdef MS_WINDOWS` block above and this simplifies the check here.

2020-10-15 18:34 UTC, ThePrez commented
Since a different (and better) approach was used to address this problem, closing

2020-10-15 18:34 UTC, closed without merging